id: PB8C8BF4F
initial_creation_type: ocr
source_metadata:
  volumes:
    145ab4433e484e859ac5fdefd0a9b953:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: ''
      total_pages: 1464
      volume_number: 47
